# Generated by Django 5.0.1 on 2024-01-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenstore_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.CharField(default='Elektronik', max_length=50),
        ),
    ]
