# Generated by Django 5.0.1 on 2024-01-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenstore_app', '0002_produk_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='img_produk',
            field=models.ImageField(default=True, upload_to='produk'),
            preserve_default=False,
        ),
    ]
