# Generated by Django 5.0.1 on 2024-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenstore_app', '0006_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
