# Generated by Django 5.0 on 2024-02-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenstore_app', '0009_remove_produk_kategori_delete_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.CharField(max_length=100)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.CharField(max_length=255)),
                ('jumlah_items', models.PositiveIntegerField()),
                ('total_harga', models.IntegerField()),
                ('pesanan_detail', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('RETURN', 'Return')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
