# Generated by Django 4.2.6 on 2024-02-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenstore_app', '0014_alter_pesanan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.CharField(max_length=100),
        ),
    ]
